name: voice-cloning-vits
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - matplotlib>=3.5.0
  - pandas
  - pyyaml
  - librosa=0.9.2
  - scikit-learn=1.2.2
  - scipy
  - numpy=1.22
  - tensorboard
  - pip:
      - TTS
      - soundfile
      - gradio
      - unidecode
      - pyopenjtalk-prebuilt
      - jamo
      - pypinyin
      - jieba
      - protobuf
      - cn2an
      - inflect
      - eng_to_ipa
      - ko_pron
      - indic_transliteration==2.3.37
      - num_thai==0.0.5
      - opencc-python-reimplemented
      - demucs
      - git+https://github.com/openai/whisper.git
